uint8 NORMAL = 0
uint8 ECO = 1
uint8 SPORT = 2

std_msgs/Header header

bool antilock_brake_active
bool traction_control_active
bool four_wheel_drive_active
bool antilock_brake_disabled
bool antilock_brake_active_avail
bool traction_control_active_avail
bool four_wheel_drive_active_avail
bool antilock_brake_disabled_avail
uint8 drive_mode
bool drive_mode_avail
bool traction_control_disabled
bool traction_control_disabled_avail
